apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "dev"
  resource: "product"
  importDerivedRoles:
    - product_derived_roles
  rules:
    - actions:
        - create
        - read
      effect: EFFECT_ALLOW
      roles:
        - user

    - actions:
        - update
        - delete
      effect: EFFECT_ALLOW
      derivedRoles:
        - owner

    - actions:
        - create
        - read
        - update
        - delete
      effect: EFFECT_ALLOW
      derivedRoles:
        - admin
